package employee;

public enum EmployeeValidationResult {

	SUCCESS, USERNAME_OR_PASSWORD_IS_INCORRECT, SIGN_UP_FAILED, EMPTY, USERNAME_OR_PASSWORD_IS_INVALID,
	PHONE_NUMBER_INVALID, UNDER_LEGAL_AGE

}
